name: build-el7

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yum install -y make rpm-build dos2unix gcc gcc-c++
      - name: make
        run: make all
      - name: modify workdir
        run: echo %_topdir $PWD/rpmbuild > ~/.rpmmacros
      - name: build
        #run: cd rpmbuild && rpmbuild -ba SPECS/nginx-el7.spec
        run: rpmbuild -ba rpmbuild/SPECS/nginx-el7.spec
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "rpmbuild/RPMS/x86_64/**"
        env:
          GITHUB_TOKEN: ${{ secrets.NGINX_TOKEN }}
