name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yum install -y make
      - name: ls
        run: ls -R /
      - name: list
        run: ls rpmbuild/SOURCES/openssl-OpenSSL_1_1_1l.tar.gz
      - name: make
        run: make all
