name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@master
      - run: yum install -y make && make all
      - run: rpmbuild -ba rpmbuild/SPECS/nginx-el7.spec