name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yum install -y make rpm-build dos2unix gcc gcc-c++
      - name: make
        run: make all
      - name: list
        run: pwd && ls -R rpmbuild
      - run: echo %_topdir $PWD/rpmbuild > ~/.rpmmacros
      - name: build
        run: cd rpmbuild && rpmbuild -ba SPECS/nginx-el7.spec
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "rpmbuild/RPMS/x86_64/nginx-1.20.1-wl.el7.x86_64.rpm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
