name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yum install -y make rpm-build dos2unix
      - name: make
        run: make all
      - name: list
        run: ls
      - name: cat
        run: cat ~/.rpmmacros && pwd
      - name: build
        run: rpmbuild -ba rpmbuild/SPECS/nginx-el7.spec
