name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yum install -y make
      - name: list
        run: ls /__w/nginx-rpm/nginx-rpm/rpmbuild/SOURCES/openssl-OpenSSL_1_1_1l.tar.gz
      - name: make
        run: make all
      - name: build
        run: rpmbuild -ba /__w/nginx-rpm/nginx-rpm/rpmbuild/SPECS/nginx-el7.spec
